<div class="container">

    <div class="register-step-box">
        <div class="bubble shadow">

            <div class="ribbion shadow">
                <h2>
                    Step 4. Make it easy for others to find you.
                </h2>
            </div>
            <div class="triangle-l"></div>
            
            <div class="clearfix"></div>
            <div class="info" style="min-height:450px;">
                
                <div class="step4-box" style="padding-left: 0px; width: 650px; margin: 50px auto 110px;">
                    <fieldset class="fieldset">
                        <legend>Choose Username</legend>
                        <?php if(Session::instance()->get('error')) {?>
                            <div class="alert alert-danger">
                               <strong>Error !</strong>
                               <?php echo Session::instance()->get_once('error');?>
                            </div>
                        <?php } ?>
                        
                        <?php if(Session::instance()->get('success')) {?>
                            <div class="alert alert-success">
                               <strong>SUCCESS </strong>
                               <?php echo Session::instance()->get_once('success');?>
                            </div>
                        <?php } ?>

                        <form class="validate-form" method="post" role="form" style="margin-left:25px;">

                            <div class="form-group">
                                <label class="control-label" for="username">Username:</label>
                                <input class="required usernameRegex uniqueUsername check_un_avail form-control" id="selected-username" type="text" name="username"
                                    value="<?php echo $user->username;?>">
                            </div>
                            
                            <p class="text-info">The username above has been automatically generated by our system. Please type a username in the box above or choose from the below suggestions whatever is easy for you to remember. If you pick 'abc' as your username,
                            your profile can be viewed as <b>https://www.amygoz.com/abc</b>
                            </p>
                            
                            <fieldset style="margin-bottom:15px;">
                                <legend>Username Suggestions</legend>
                                <?php foreach($suggestions as $suggestion) { ?>
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="suggestion" class="un-suggestion" value="<?php echo $suggestion; ?>">
                                            <?php echo $suggestion; ?>
                                        </label>
                                    </div>
                                <?php } ?>
                            </fieldset>

                            <button type="submit" class="btn btn-secondary">Update</button>
                        </form>
                    </fieldset>
                </div>
                <a href="<?php echo url::base().'pages/skip_step'; ?>" class="pull-right">Skip this step >></a>
            </div>
        </div>
    </div>

</div>