<html>
<head>
  <title>Check Register Api</title>
</head>
<body>
<!-- All the files that are required -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link href='https://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
<script src="https://www.callitme.com/js/jquery-1.10.2.min.js?v=1.1" type="text/javascript"></script>

                            <div class="form-group">
                                <label class="control-label" for="username">Username:</label>
                                <input  id="newusername" type="text" name="newusername" value="">
                                <input type="hidden" id="username" name="username" value="pranay">
                            </div>
                            
                            <p class="text-info">The username above has been automatically generated by our system. Please type a username
                            in the box above or choose from the below suggestions whatever is easy for you to remember. If you pick 'abc' as your username,
                            your profile can be viewed as <b>https://www.callitme.com/abc</b>
                            </p>
                            
                            

                            <button id="submit" class="btn btn-secondary">Update</button>
                        
                        </body>
</html>
<script>
  $('document').ready(function(){
    $('#submit').click(function() {
      //var fdata = $('#email_form').serialize();
        
      var newusername = $('#newusername').val();
      var username = $('#username').val();

      /*var fname = $('#first_name').val();
      var sex = $('#sex').val();
      var lname = $('#last_name').val();
      var phone_number = $('#phone_number').val();
      var month = $('#month').val();
      var day = $('#day').val();
      var year = $('#year').val();
      var phase_of_life = $('#phase_of_life').val();*/
      //alert(fdata);

     $.ajax({
        //alert('asds');
        method : 'POST',
        type: 'json',
        data: {newusername:newusername, username:username}, // Data sent to server, a set of key/value pairs (i.e. form fields and values)
        url : 'https://www.callitme.com/accessapi/newuser_username',
        success: function(data)
        {
          
          if(data.status == '1')
          {
            //$("p").html
            //$('h3').html("<h4 style='color:green'>"+data.message+' and user Api key is'+data.user_id+"</h4>"); //= ;
            alert(data.message);
            //window.location.href = "https://www.callitme.com/TestApi/register/photo.php";
          }
          else
          {
            alert(data.message);//= ;
          }
        }
      })
        //var serverUrl = ;
        
    })
  });
</script>