<?php defined('SYSPATH') OR die('No direct access allowed.');

return array
(
    'phase_of_life' => array(
        1 => 'Single',
        2 => 'Hard to explain',
        3 => 'Married',
        4 => 'Hanging out with someone',
        5 => 'Divorced',
        6 => 'Engaged',
        7 => 'Widowed',
    ),
    'issues' => array(
        1 => 'Account/Settings',
        2 => 'Billing/Payments/Fees',
        3 => 'Compromised Passwords',
        4 => 'Messages',
        5 => 'Login/Password',
        6 => 'Privacy/Abuse',
        7 => 'Profile Management',
        8 => 'Delete Profile',
        9 => 'Others',
    ),
    'show_column' => array(
        'first_name' => "first name",
        'last_name' => "last name",
        'sex' => "sex",
        'phase_of_life' => "phase of life",
        'phone' => "phone number",
        'location' => "location",
        'home_town' => "home town",
        'education' => "education",
        'employment' => "employment",
        'designation' => "designation",
        'website' => "website",
        'about' => "about",
    ),
    'has_s' => array(
        'first_name' => false,
        'last_name' => false,
        'sex' => false,
        'phase_of_life' => false,
        'phone' => false,
        'location' => false,
        'home_town' => true,
        'education' => false,
        'employment' => false,
        'designation' => true,
        'website' => false,
        'about' => false,
    ),
    'update_text' => array(
        'first_name' => "has updated 'first name' from '{old}' to '{new}'.",
        'last_name' => "has updated 'last name' from '{old}' to '{new}'.",
        'sex' => "has updated 'sex' from '{old}' to '{new}'.",
        'phase_of_life' => "has updated 'phase of life' from '{old}' to '{new}'.",
        'phone' => "has updated 'phone' from '{old}' to '{new}'.",
        'location' => "now lives in '{new}'.",
        'home_town' => "home town is now '{new}'.",
        'education' => "now attends '{new}'.",
        'employment' => "now works at '{new}'.",
        'designation' => "new job title is '{new}'.",
        'website' => "has updated 'website' from '{old}' to '{new}'.",
        'about' => "has updated 'about' from '{old}' to '{new}'.",
    ),
    'add_text' => array(
        'first_name' => "has added 'first name' as '{new}'.",
        'last_name' => "has added 'last name' as '{new}'.",
        'sex' => "has added 'sex' as '{new}'.",
        'phase_of_life' => "has added 'phase of life' as '{new}'.",
        'phone' => "has added 'phone' as '{new}'.",
        'location' => "lives in '{new}'.",
        'home_town' => "hometown is '{new}'.",
        'education' => "attended '{new}'.",
        'employment' => "works at '{new}'.",
        'designation' => "job title is '{new}'.",
        'website' => "has added 'website' as '{new}'.",
        'about' => "has added 'about' as '{new}'.",
    ),
   // 'version' => '1.1'
    'version' => '1.1'
);