<div class="container" style="padding-top: 38px;padding-bottom: 47px;">
    <div class="register-step-box">
        <div class="">
            <div class="text-center">
                <h4>
                    Step 4. Make it easy for others to find you.
                </h4>
            </div>
            <div class="clearfix"></div>
            <div class="info">
                
                <div class="step4-box">
                    <fieldset class="fieldset">
                        <h4>Choose Username</h4>
                        <?php if(Session::instance()->get('error')) {?>
                            <div class="alert alert-danger">
                               <strong>Error !</strong>
                               <?php echo Session::instance()->get_once('error');?>
                            </div>
                        <?php } ?>
                        
                        <?php if(Session::instance()->get('success')) {?>
                            <div class="alert alert-success">
                               <strong>SUCCESS </strong>
                               <?php echo Session::instance()->get_once('success');?>
                            </div>
                        <?php } ?>

                        <form class="validate-form" method="post" role="form" style="margin-left:25px;">

                            <div class="form-group">
                                <label class="control-label" for="username">Username:</label>
                                <input class="required usernameRegex uniqueUsername check_un_avail form-control" id="selected-username" type="text" name="username"
                                    value="<?php echo $user->username;?>">
                            </div>
                            <fieldset style="margin-bottom:15px;">
                                <h4>Username Suggestions</h4>
                                <?php foreach($suggestions as $suggestion) { ?>
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="suggestion" class="un-suggestion" value="<?php echo $suggestion; ?>">
                                            <?php echo $suggestion; ?>
                                        </label>
                                    </div>
                                <?php } ?>
                            </fieldset>
                            <div class="row">
                            <p class="text-info">The username above has been automatically generated by our system. Please type a username
                            in the box above or choose from the below suggestions whatever is easy for you to remember. If you pick 'abc' as your username,
                            your profile can be viewed as <b>https://www.callitme.com/abc</b>
                            </p>
                            </div>
                            <div class="col-xs-12">
                            <button type="submit" class="btn no-bg-image btn-block" style="/*! width: 100%; */background: none;background:#f06163;color: #fff;font-weight: 500;border-radius: 40px;padding: 10px 46px;font-size: 18px;">Update</button>
                            </div>
                        </form>
                    </fieldset>
                </div>
                <div class="col-xs-12 text-center">&nbsp;</div>
                <div class="col-xs-12 text-center">
                <a href="<?php echo url::base().'pages/skip_step'; ?>" style="color: #0c0c0c;font-size: 18px !important;font-weight: 500;">Skip this step >></a>
            </div>
            </div>
        </div>
    </div>

</div>